# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af01f6c4113e5047cd2ec1f5c894e98e7627ded2b7d7668ed5942f9a7e2d0d77b6a664bb0e6ae820911853934553cbf568ffe30826a1863846876790f92ef153

test:
  secret_key_base: 53f21397d7dab7c43caec942b8488d4f81ccab4a830017973bd817aef355af432db5e48ccd33a123f3286c088e176435557ec9e0aeb8c49502a889433dc06f1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
